# Generated by Django 3.1.1 on 2021-04-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20210410_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='subtitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
