# Generated by Django 3.1.1 on 2021-05-21 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_courses_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='dateofcourse',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 0, 5, 18, 826172)),
        ),
        migrations.AddField(
            model_name='courses',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
