# Generated by Django 3.2.3 on 2021-05-22 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_alter_courses_dateofcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='dateofcourse',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 23, 56, 22, 500449)),
        ),
    ]
