# Generated by Django 3.2.3 on 2021-05-23 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_alter_courses_dateofcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='dateofcourse',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 23, 21, 32, 25, 768352)),
        ),
    ]
