# Generated by Django 3.2.3 on 2021-05-23 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_alter_courses_dateofcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='dateofcourse',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 0, 17, 13, 626519)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='subtitle',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.TextField(),
        ),
    ]
